// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v3.20.3
// source: proto/create_link.proto

package golang

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestCreateLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	URL           string                 `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCreateLink) Reset() {
	*x = RequestCreateLink{}
	mi := &file_proto_create_link_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCreateLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCreateLink) ProtoMessage() {}

func (x *RequestCreateLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_create_link_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCreateLink.ProtoReflect.Descriptor instead.
func (*RequestCreateLink) Descriptor() ([]byte, []int) {
	return file_proto_create_link_proto_rawDescGZIP(), []int{0}
}

func (x *RequestCreateLink) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

type ResponseCreateLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	CreateAt      int64                  `protobuf:"varint,2,opt,name=CreateAt,proto3" json:"CreateAt,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=ExpiresAt,proto3" json:"ExpiresAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseCreateLink) Reset() {
	*x = ResponseCreateLink{}
	mi := &file_proto_create_link_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseCreateLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCreateLink) ProtoMessage() {}

func (x *ResponseCreateLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_create_link_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCreateLink.ProtoReflect.Descriptor instead.
func (*ResponseCreateLink) Descriptor() ([]byte, []int) {
	return file_proto_create_link_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseCreateLink) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ResponseCreateLink) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *ResponseCreateLink) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type RequestGetLinkByHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGetLinkByHash) Reset() {
	*x = RequestGetLinkByHash{}
	mi := &file_proto_create_link_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGetLinkByHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetLinkByHash) ProtoMessage() {}

func (x *RequestGetLinkByHash) ProtoReflect() protoreflect.Message {
	mi := &file_proto_create_link_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetLinkByHash.ProtoReflect.Descriptor instead.
func (*RequestGetLinkByHash) Descriptor() ([]byte, []int) {
	return file_proto_create_link_proto_rawDescGZIP(), []int{2}
}

func (x *RequestGetLinkByHash) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type ResponseGetLinkByHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	URL           string                 `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGetLinkByHash) Reset() {
	*x = ResponseGetLinkByHash{}
	mi := &file_proto_create_link_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetLinkByHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetLinkByHash) ProtoMessage() {}

func (x *ResponseGetLinkByHash) ProtoReflect() protoreflect.Message {
	mi := &file_proto_create_link_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetLinkByHash.ProtoReflect.Descriptor instead.
func (*ResponseGetLinkByHash) Descriptor() ([]byte, []int) {
	return file_proto_create_link_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseGetLinkByHash) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

var File_proto_create_link_proto protoreflect.FileDescriptor

var file_proto_create_link_proto_rawDesc = string([]byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x6c,
	0x69, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x6f, 0x72, 0x67, 0x2e, 0x6c,
	0x69, 0x6e, 0x6b, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x22, 0x25, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x4c, 0x22, 0x62, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a,
	0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x22, 0x2a, 0x0a, 0x14, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x42, 0x79, 0x48,
	0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x22, 0x29, 0x0a, 0x15, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x42, 0x79, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x10, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55,
	0x52, 0x4c, 0x32, 0xde, 0x01, 0x0a, 0x0d, 0x4c, 0x69, 0x6e, 0x6b, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x12, 0x61, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69,
	0x6e, 0x6b, 0x12, 0x28, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x1a, 0x29, 0x2e, 0x6f,
	0x72, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x6a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4c, 0x69,
	0x6e, 0x6b, 0x42, 0x79, 0x48, 0x61, 0x73, 0x68, 0x12, 0x2b, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x6c,
	0x69, 0x6e, 0x6b, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x42,
	0x79, 0x48, 0x61, 0x73, 0x68, 0x1a, 0x2c, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x6c, 0x69, 0x6e, 0x6b,
	0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x42, 0x79, 0x48,
	0x61, 0x73, 0x68, 0x42, 0x45, 0x5a, 0x43, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x66, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x68, 0x6b, 0x61, 0x72, 0x69, 0x6d, 0x69, 0x2f,
	0x6c, 0x69, 0x6e, 0x6b, 0x2d, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2f, 0x61,
	0x70, 0x69, 0x2d, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x73, 0x72, 0x63, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_proto_create_link_proto_rawDescOnce sync.Once
	file_proto_create_link_proto_rawDescData []byte
)

func file_proto_create_link_proto_rawDescGZIP() []byte {
	file_proto_create_link_proto_rawDescOnce.Do(func() {
		file_proto_create_link_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_create_link_proto_rawDesc), len(file_proto_create_link_proto_rawDesc)))
	})
	return file_proto_create_link_proto_rawDescData
}

var file_proto_create_link_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_create_link_proto_goTypes = []any{
	(*RequestCreateLink)(nil),     // 0: org.link_shortener.v1.RequestCreateLink
	(*ResponseCreateLink)(nil),    // 1: org.link_shortener.v1.ResponseCreateLink
	(*RequestGetLinkByHash)(nil),  // 2: org.link_shortener.v1.RequestGetLinkByHash
	(*ResponseGetLinkByHash)(nil), // 3: org.link_shortener.v1.ResponseGetLinkByHash
}
var file_proto_create_link_proto_depIdxs = []int32{
	0, // 0: org.link_shortener.v1.LinkShortener.CreateLink:input_type -> org.link_shortener.v1.RequestCreateLink
	2, // 1: org.link_shortener.v1.LinkShortener.GetLinkByHash:input_type -> org.link_shortener.v1.RequestGetLinkByHash
	1, // 2: org.link_shortener.v1.LinkShortener.CreateLink:output_type -> org.link_shortener.v1.ResponseCreateLink
	3, // 3: org.link_shortener.v1.LinkShortener.GetLinkByHash:output_type -> org.link_shortener.v1.ResponseGetLinkByHash
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_create_link_proto_init() }
func file_proto_create_link_proto_init() {
	if File_proto_create_link_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_create_link_proto_rawDesc), len(file_proto_create_link_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_create_link_proto_goTypes,
		DependencyIndexes: file_proto_create_link_proto_depIdxs,
		MessageInfos:      file_proto_create_link_proto_msgTypes,
	}.Build()
	File_proto_create_link_proto = out.File
	file_proto_create_link_proto_goTypes = nil
	file_proto_create_link_proto_depIdxs = nil
}
